version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: adocao_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_adocao
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql